### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by putianyi889** [putianyi889/JFP-demo#3]
- [X] Algebraic convergence of polynomial approximants to a fractional integral. [singularity.jl](https://github.com/putianyi889/JFP-demo/blob/main/singularity.jl)
- [X] An example of JFP basis functions. [jfp_plot.jl](https://github.com/putianyi889/JFP-demo/blob/main/jfp_plot.jl)
- [X] Errors in log10 scale from using Algorithm 1. [dense_division.jl](https://github.com/putianyi889/JFP-demo/blob/main/dense_division.jl)
- [X] Errors in log10 scale from using Algorithm 2. [foward_recurrence.jl](https://github.com/putianyi889/JFP-demo/blob/main/foward_recurrence.jl)
- [X] Errors produced by the JFP method for different fractional orders. [u+Iu=1.jl](https://github.com/putianyi889/JFP-demo/blob/main/u%2BIu%3D1.jl)
- [X] RHS singularity. [u+Iu=sqrt(1+x).jl](https://github.com/putianyi889/JFP-demo/blob/main/u%2BIu%3D1.jl)
- [X] u+λIu=1 from sum space: double precision, high precision, numerical solutions and condition numbers. [FHE_sumspace.jl](https://github.com/putianyi889/JFP-demo/blob/main/FHE_sumspace.jl)
- [X] u+λIu=1 from JFP: errors, coefficients and condition numbers. [FHE_JFP.jl](https://github.com/putianyi889/JFP-demo/blob/main/FHE_JFP.jl)
- [X] Contour and wireframe plots for fractionsl wave equation. [fractional_heat_wave_equation.jl](https://github.com/putianyi889/JFP-demo/blob/main/fractional_heat_wave_equation.jl)
- [X] General FIEs and FDEs: multiple orders, variable coefficient, Bagley-Torvik [GeneralExamples.jl](https://github.com/putianyi889/JFP-demo/blob/main/GeneralExamples.jl)
- [X] fractional Airy equation [Airy.jl](https://github.com/putianyi889/JFP-demo/blob/main/Airy.jl)
- [X] PS: overview of error growth. [PS_error_overview.jl](https://github.com/putianyi889/JFP-demo/blob/main/PS_error_overview.jl)
- [X] PS: errors from different initial values. [PS_constant_growth.jl](https://github.com/putianyi889/JFP-demo/blob/main/PS_constant_growth.jl)
- [x] PS: insight of error growth.
